package ui;

import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.MalformedURLException;
import java.net.URL;

import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JPopupMenu;
import bot.Bot;

import util.Configuration;
import util.io.HttpClient;
import loader.RSLoader;

/**
 * 
 * @author Tim
 */
public class Login extends javax.swing.JFrame {

	public static BotFrame botframe;

	private void writePath() throws IOException {
		String s = Configuration.Paths.getPathCache();
		FileWriter outFile = new FileWriter(s);
		PrintWriter out = new PrintWriter(outFile);
		out.println(Configuration.Paths.getRunningJarPath());
		out.close();
		outFile.close();
		if (!Configuration.CompilerExists()) {
			HttpClient.download(new URL(
					"http://www.runeshark.net/bot/Compile.bat"), new File(
					Configuration.Paths.getHomeDirectory() + File.separator
							+ "Compile.bat"));
			HttpClient.download(new URL(
					"http://www.runeshark.net/bot/FindJDK.bat"), new File(
					Configuration.Paths.getHomeDirectory() + File.separator
							+ "FindJDK.bat"));
		}
		if (!Configuration.MapExists()) {
			HttpClient.download(new URL(
					"http://www.runeshark.net/bot/runescape_surface.png"),
					new File(Configuration.Paths.getHomeDirectory()
							+ File.separator + "runescape_surface.png"));
		}
	}

	private static void startBot() {
		System.out.println("Loading...");
		RSLoader r = new RSLoader();
		botframe = new BotFrame(r.loadClient());
		new Bot();
		BotFrame.log("Welcome to RuneShark.");
	}

	@SuppressWarnings("deprecation")
	public static boolean submit() {
		String user = jTextField1.getText();
		String pass = jPasswordField1.getText();
		String URL = "http://runeshark.net/bot/LoginCheck.php?username="
				+ user.replaceAll(" ", "%20") + "&password="
				+ pass.replaceAll(" ", "%20");
		BufferedReader br = null;
		try {
			br = new BufferedReader(new InputStreamReader(
					new URL(URL).openStream()));
		} catch (MalformedURLException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}
		String input;
		try {
			if ((input = br.readLine()) != null) {
				System.out.println(input);
				if (input.equalsIgnoreCase("valid login")) {
					startBot();
					return true;
				}
			}
		} catch (IOException e) {
			e.printStackTrace();
		}
		return false;
	}

	/** Creates new form Login */
	public Login() {
		try {
			writePath();
		} catch (IOException e) {
			e.printStackTrace();
		}
		JFrame.setDefaultLookAndFeelDecorated(true);
		JDialog.setDefaultLookAndFeelDecorated(true);
		JPopupMenu.setDefaultLightWeightPopupEnabled(false);
		setLocationRelativeTo(null);
		initComponents();
		//old url : "http://img18.imageshack.us/img18/629/runesharklogo.png"
		jLabel5.setText("<html><img src=\"http://i.imgur.com/esjnj.png"
				+ "\">" + "</html>");
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jTextField1 = new javax.swing.JTextField();
		jPasswordField1 = new javax.swing.JPasswordField();
		jButton1 = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jButton2 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Login");

		jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				jPasswordField1KeyPressed(evt);
			}
		});

		jButton1.setText("Submit");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel2.setText("Username:");

		jLabel3.setText("Password:");

		jButton2.setText("Login as Guest");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jLabel5.setText("jLabel5");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		jLabel5)
																.addGap(39, 39,
																		39)
																.addComponent(
																		jLabel1)
																.addGap(18, 18,
																		18)
																.addComponent(
																		jLabel4))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(121,
																		121,
																		121)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(59,
																										59,
																										59)
																								.addComponent(
																										jLabel3))
																				.addComponent(
																						jPasswordField1)
																				.addComponent(
																						jTextField1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						154,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(54,
																										54,
																										54)
																								.addComponent(
																										jLabel2))))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(42, 42,
																		42)
																.addComponent(
																		jButton1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		143,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(18, 18,
																		18)
																.addComponent(
																		jButton2,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		140,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap(60, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		jLabel1))
												.addComponent(jLabel4)
												.addComponent(jLabel5))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										65, Short.MAX_VALUE)
								.addComponent(jLabel2)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jTextField1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jLabel3)
								.addGap(11, 11, 11)
								.addComponent(jPasswordField1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton1)
												.addComponent(jButton2))
								.addGap(45, 45, 45)));

		pack();
	}// </editor-fold>

	private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {
		if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
			dispose();
			if (submit()) {
			} else {
				setVisible(true);
				jTextField1.setText("");
				jPasswordField1.setText("");
			}
		}
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		setVisible(false);
		if (!jTextField1.getText().equals("guest")) {
			if (submit()) {
				dispose();
			} else {
				setVisible(true);
				jTextField1.setText("");
				jPasswordField1.setText("");
			}
		} else {
			startBot();
		}
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		setVisible(false);
		startBot();
	}

	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private static javax.swing.JPasswordField jPasswordField1;
	private static javax.swing.JTextField jTextField1;
	// End of variables declaration
}
